# FROM node:14-alpine

# WORKDIR /app

# # COPY rollup.config.js ./
# # COPY package*.json ./

# # RUN npm install

# # Copy package.json and package-lock.json (if available)
# COPY package.json package-lock.json ./
# COPY ./src ./src
# # COPY ./public ./public

# # Install dependencies
# RUN npm install

# # Copy the rest of the application code
# COPY . .

# # Build the Svelte app
# RUN npm run build

# Use the official Node.js 18 image as the base image for the build stage
FROM node:18-alpine AS build

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the Svelte app
RUN npm run build

EXPOSE 5173

ENV HOST=0.0.0.0

CMD [ "npm", "run", "dev" ]


# # Use the official Node.js 18 image as the base image for the build stage
# FROM node:18-alpine AS build

# # Set the working directory in the container
# WORKDIR /app

# # Copy package.json and package-lock.json (if available)
# COPY package.json package-lock.json ./

# # Install dependencies
# RUN npm install

# # Copy the rest of the application code
# COPY . .

# # Build the Svelte app
# RUN npm run build

# # Use the official Nginx image as the base image for serving the app
# FROM nginx:alpine

# # Copy the built app from the previous stage
# COPY --from=build /app/.svelte-kit/output /usr/share/nginx/html

# # Expose port 80
# EXPOSE 80

# # Start Nginx server
# CMD ["nginx", "-g", "daemon off;"]